apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: secretsanta-ingress
 annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 ingressClassName: nginx
 rules:
  - host: secretsanta.local
    http:
     paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: secretsanta-service
             port:
              number: 80